name: example_console_app
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  dio: ^4.0.6
  logger: ^1.1.0
  pretty_dio_logger: ^1.2.0-beta-1
  web3dart: ^2.4.0
  bip39: ^1.0.6
  ed25519_hd_key: ^2.2.0
  hex: ^0.2.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
